# Generated by Django 4.0.5 on 2022-06-17 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(default='COG6776', max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('raised_by', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(choices=[('QHF390', 'esakki'), ('MZR006', 'steve')], max_length=25)),
                ('assigned_email', models.EmailField(max_length=255)),
                ('attachment', models.FileField(upload_to='bugs/TicketModel/', verbose_name='adding bug screenshot')),
                ('priority', models.IntegerField(choices=[(1, 'VeryHigh'), (2, 'HIGH'), (3, 'LOW')])),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
