# Generated by Django 4.0.5 on 2022-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='assigned_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketId',
            field=models.CharField(default='COG6304', max_length=25),
        ),
    ]
