# Generated by Django 4.0.5 on 2022-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketmodel_ticketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='assigned_email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='raised_by',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketId',
            field=models.CharField(default='COG3533', max_length=25),
        ),
    ]
