# Generated by Django 4.0.5 on 2022-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticketmodel_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketId',
            field=models.CharField(default='COG2712', max_length=25),
        ),
    ]
