# Generated by Django 4.0.5 on 2022-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticketmodel_ticketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='attachment',
            field=models.FileField(default=None, upload_to='bugs/TicketModel/', verbose_name='adding bug screenshot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketId',
            field=models.CharField(default='COG7834', max_length=25),
        ),
    ]
