apiVersion: apps/v1
kind: Deployment
metadata:
  name: basics-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: basics-hello
  template:
    metadata:
      labels:
        app: basics-hello
    spec:
      containers:
      - name: basics-hello
        image: esak2021/basics-hello:2.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
