apiVersion: v1
kind: Service
metadata:
  name: web2nginx
spec:
  type: LoadBalancer
  selector:
    app: web2nginx
  ports:
  - port: 3333
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web2nginx
  template:
    metadata:
      labels:
        app: web2nginx
    spec:
      containers:
      - name: web2nginx
        image: esak2021/web2nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

