# Generated by Django 4.0.5 on 2022-06-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinguser',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
